export default {
    neutral: {
        white: {
            list: [
                "/icons/images/Black/white/list/Icon-List-Module_2_Support_RGB_black.png",
                "/icons/images/Black/white/list/Icon-List-Module_2_View-Account_RGB_black.png",
                "/icons/images/Black/white/list/Icon-List-Module_End_to_end_security_RGB_black.png",
                "/icons/images/Black/white/list/Icon-List-Module_Financial_Services_RGB_black.png",
                "/icons/images/Black/white/list/Icon-List-Module_Gear_RGB_black.png",
                "/icons/images/Black/white/list/Icon-List-Module_Ink_RGB_black.png",
                "/icons/images/Black/white/list/Icon-List-Module_Inks_RGB_black.png",
                "/icons/images/Black/white/list/Icon-List-Module_Instant-Ink_RGB_black.png",
                "/icons/images/Black/white/list/Icon-List-Module_Laptop_RGB_black.png",
                "/icons/images/Black/white/list/Icon-List-Module_Legendary_HP_relaibility_RGB_black.png",
                "/icons/images/Black/white/list/Icon-List-Module_Ok_RGB_black.png",
                "/icons/images/Black/white/list/Icon-List-Module_On_the_fly_RGB_black.png",
                "/icons/images/Black/white/list/Icon-List-Module_Planet_pillar_RGB_black.png",
                "/icons/images/Black/white/list/Icon-List-Module_Printer_RGB_black.png",
                "/icons/images/Black/white/list/Icon-List-Module_Quick Setup_RGB_black.png",
                "/icons/images/Black/white/list/Icon-List-Module_Repair_RGB_black.png",
                "/icons/images/Black/white/list/Icon-List-Module_Setup_supplies_RGB_black.png",
                "/icons/images/Black/white/list/Icon-List-Module_Shopping_cart_RGB_black.png",
                "/icons/images/Black/white/list/Icon-List-Module_Smart_printer_RGB_black.png",
                "/icons/images/Black/white/list/Icon-List-Module_Star_recomendation_RGB_black.png",
                "/icons/images/Black/white/list/Icon-List-Module_Sustainable_packaging_RGB_black.png",
                "/icons/images/Black/white/list/Icon-List-Module_Thumbs_up_RGB_black.png",
                "/icons/images/Black/white/list/Icon-List-Module_User_authentication_RGB_black.png",
                "/icons/images/Black/white/list/Icon-List-Module_Web_connected_printer_RGB_black.png",
            ],
            link: [
                "/icons/images/Black/white/link/Link-Icon-Module_2_Instant-Ink_RGB_black.png",
                "/icons/images/Black/white/link/Link-Icon-Module_2_Support_RGB_black.png",
                "/icons/images/Black/white/link/Link-Icon-Module_2_View-Account_RGB_black.png",
                "/icons/images/Black/white/link/Link-Icon-Module_End_to_end_security_RGB_black.png",
                "/icons/images/Black/white/link/Link-Icon-Module_Financial_Services_RGB_black.png",
                "/icons/images/Black/white/link/Link-Icon-Module_Gear_RGB_black.png",
                "/icons/images/Black/white/link/Link-Icon-Module_Ink_RGB_black.png",
                "/icons/images/Black/white/link/Link-Icon-Module_Inks_RGB_black.png",
                "/icons/images/Black/white/link/Link-Icon-Module_Laptop_RGB_black.png",
                "/icons/images/Black/white/link/Link-Icon-Module_Legendary_HP_relaibility_RGB_black.png",
                "/icons/images/Black/white/link/Link-Icon-Module_Ok_RGB_black.png",
                "/icons/images/Black/white/link/Link-Icon-Module_On_the_fly_RGB_black.png",
                "/icons/images/Black/white/link/Link-Icon-Module_Planet_pillar_RGB_black.png",
                "/icons/images/Black/white/link/Link-Icon-Module_Printer_RGB_black.png",
                "/icons/images/Black/white/link/Link-Icon-Module_Quick Setup_RGB_black.png",
                "/icons/images/Black/white/link/Link-Icon-Module_Repair_RGB_black.png",
                "/icons/images/Black/white/link/Link-Icon-Module_Setup_supplies_RGB_black.png",
                "/icons/images/Black/white/link/Link-Icon-Module_Shopping_cart_RGB_black.png",
                "/icons/images/Black/white/link/Link-Icon-Module_Smart_printer_RGB_black.png",
                "/icons/images/Black/white/link/Link-Icon-Module_Star_recomendation_RGB_black.png",
                "/icons/images/Black/white/link/Link-Icon-Module_Sustainable_packaging_RGB_black.png",
                "/icons/images/Black/white/link/Link-Icon-Module_Thumbs_up_RGB_black.png",
                "/icons/images/Black/white/link/Link-Icon-Module_User_authentication_RGB_black.png",
                "/icons/images/Black/white/link/Link-Icon-Module_Web_connected_printer_RGB_black.png",
            ],
        },
    },
    blue: {
        color: {
            list: [
                "/icons/images/Blue/color/list/Icon-List-Module_2_Support_RGB_black_blue-circle.png",
                "/icons/images/Blue/color/list/Icon-List-Module_2_View-Account_RGB_black_blue-circle.png",
                "/icons/images/Blue/color/list/Icon-List-Module_End_to_end_security_RGB_black_blue-circle.png",
                "/icons/images/Blue/color/list/Icon-List-Module_Financial_Services_RGB_black_blue-circle.png",
                "/icons/images/Blue/color/list/Icon-List-Module_Gear_RGB_black_blue-circle.png",
                "/icons/images/Blue/color/list/Icon-List-Module_Ink_RGB_black_blue-circle.png",
                "/icons/images/Blue/color/list/Icon-List-Module_Inks_RGB_black_blue-circle.png",
                "/icons/images/Blue/color/list/Icon-List-Module_Instant-Ink_RGB_black_blue-circle.png",
                "/icons/images/Blue/color/list/Icon-List-Module_Laptop_RGB_black_blue-circle.png",
                "/icons/images/Blue/color/list/Icon-List-Module_Legendary_HP_relaibility_RGB_black_blue-circle.png",
                "/icons/images/Blue/color/list/Icon-List-Module_Ok_RGB_black_blue-circle.png",
                "/icons/images/Blue/color/list/Icon-List-Module_On_the_fly_RGB_black_blue-circle.png",
                "/icons/images/Blue/color/list/Icon-List-Module_Planet_pillar_RGB_black_blue-circle.png",
                "/icons/images/Blue/color/list/Icon-List-Module_Printer_RGB_black_blue-circle.png",
                "/icons/images/Blue/color/list/Icon-List-Module_Quick Setup_RGB_black_blue-circle.png",
                "/icons/images/Blue/color/list/Icon-List-Module_Repair_RGB_black_blue-circle.png",
                "/icons/images/Blue/color/list/Icon-List-Module_Setup_supplies_RGB_black_blue-circle.png",
                "/icons/images/Blue/color/list/Icon-List-Module_Shopping_cart_RGB_black_blue-circle.png",
                "/icons/images/Blue/color/list/Icon-List-Module_Smart_printer_RGB_black_blue-circle.png",
                "/icons/images/Blue/color/list/Icon-List-Module_Star_recomendation_RGB_black_blue-circle.png",
                "/icons/images/Blue/color/list/Icon-List-Module_Sustainable_packaging_RGB_black_blue-circle.png",
                "/icons/images/Blue/color/list/Icon-List-Module_Thumbs_up_RGB_black_blue-circle.png",
                "/icons/images/Blue/color/list/Icon-List-Module_User_authentication_RGB_black_blue-circle.png",
                "/icons/images/Blue/color/list/Icon-List-Module_Web_connected_printer_RGB_black_blue-circle.png",
            ],
            link: [
                "/icons/images/Blue/color/link/Link-Icon-Module_2_Instant-Ink_RGB_black_blue-circle.png",
                "/icons/images/Blue/color/link/Link-Icon-Module_2_Support_RGB_black_blue-circle.png",
                "/icons/images/Blue/color/link/Link-Icon-Module_2_View-Account_RGB_black_blue-circle.png",
                "/icons/images/Blue/color/link/Link-Icon-Module_End_to_end_security_RGB_black_blue-circle.png",
                "/icons/images/Blue/color/link/Link-Icon-Module_Financial_Services_RGB_black_blue-circle.png",
                "/icons/images/Blue/color/link/Link-Icon-Module_Gear_RGB_black_blue-circle.png",
                "/icons/images/Blue/color/link/Link-Icon-Module_Ink_RGB_black_blue-circle.png",
                "/icons/images/Blue/color/link/Link-Icon-Module_Inks_RGB_black_blue-circle.png",
                "/icons/images/Blue/color/link/Link-Icon-Module_Laptop_RGB_black_blue-circle.png",
                "/icons/images/Blue/color/link/Link-Icon-Module_Legendary_HP_relaibility_RGB_black_blue-circle.png",
                "/icons/images/Blue/color/link/Link-Icon-Module_Ok_RGB_black_blue-circle.png",
                "/icons/images/Blue/color/link/Link-Icon-Module_On_the_fly_RGB_black_blue-circle.png",
                "/icons/images/Blue/color/link/Link-Icon-Module_Planet_pillar_RGB_black_blue-circle.png",
                "/icons/images/Blue/color/link/Link-Icon-Module_Printer_RGB_black_blue-circle.png",
                "/icons/images/Blue/color/link/Link-Icon-Module_Quick Setup_RGB_black_blue-circle.png",
                "/icons/images/Blue/color/link/Link-Icon-Module_Repair_RGB_black_blue-circle.png",
                "/icons/images/Blue/color/link/Link-Icon-Module_Setup_supplies_RGB_black_blue-circle.png",
                "/icons/images/Blue/color/link/Link-Icon-Module_Shopping_cart_RGB_black_blue-circle.png",
                "/icons/images/Blue/color/link/Link-Icon-Module_Smart_printer_RGB_black_blue-circle.png",
                "/icons/images/Blue/color/link/Link-Icon-Module_Star_recomendation_RGB_black_blue-circle.png",
                "/icons/images/Blue/color/link/Link-Icon-Module_Sustainable_packaging_RGB_black_blue-circle.png",
                "/icons/images/Blue/color/link/Link-Icon-Module_Thumbs_up_RGB_black_blue-circle.png",
                "/icons/images/Blue/color/link/Link-Icon-Module_User_authentication_RGB_black_blue-circle.png",
                "/icons/images/Blue/color/link/Link-Icon-Module_Web_connected_printer_RGB_black_blue-circle.png",
            ],
        },
        white: {
            list: [
                "/icons/images/Blue/white/list/Icon-List-Module_2_Support_RGB_blue_white-circle.png",
                "/icons/images/Blue/white/list/Icon-List-Module_2_View-Account_RGB_blue_white-circle.png",
                "/icons/images/Blue/white/list/Icon-List-Module_End_to_end_security_RGB_blue_white-circle.png",
                "/icons/images/Blue/white/list/Icon-List-Module_Financial_Services_RGB_blue_white-circle.png",
                "/icons/images/Blue/white/list/Icon-List-Module_Gear_RGB_blue_white-circle.png",
                "/icons/images/Blue/white/list/Icon-List-Module_Ink_RGB_blue_white-circle.png",
                "/icons/images/Blue/white/list/Icon-List-Module_Inks_RGB_blue_white-circle.png",
                "/icons/images/Blue/white/list/Icon-List-Module_Instant-Ink_RGB_blue_white-circle.png",
                "/icons/images/Blue/white/list/Icon-List-Module_Laptop_RGB_blue_white-circle.png",
                "/icons/images/Blue/white/list/Icon-List-Module_Legendary_HP_relaibility_RGB_blue_white-circle.png",
                "/icons/images/Blue/white/list/Icon-List-Module_Ok_RGB_blue_white-circle.png",
                "/icons/images/Blue/white/list/Icon-List-Module_On_the_fly_RGB_blue_white-circle.png",
                "/icons/images/Blue/white/list/Icon-List-Module_Planet_pillar_RGB_blue_white-circle.png",
                "/icons/images/Blue/white/list/Icon-List-Module_Printer_RGB_blue_white-circle.png",
                "/icons/images/Blue/white/list/Icon-List-Module_Quick Setup_RGB_blue_white-circle.png",
                "/icons/images/Blue/white/list/Icon-List-Module_Repair_RGB_blue_white-circle.png",
                "/icons/images/Blue/white/list/Icon-List-Module_Setup_supplies_RGB_blue_white-circle.png",
                "/icons/images/Blue/white/list/Icon-List-Module_Shopping_cart_RGB_blue_white-circle.png",
                "/icons/images/Blue/white/list/Icon-List-Module_Smart_printer_RGB_blue_white-circle.png",
                "/icons/images/Blue/white/list/Icon-List-Module_Star_recomendation_RGB_blue_white-circle.png",
                "/icons/images/Blue/white/list/Icon-List-Module_Sustainable_packaging_RGB_blue_white-circle.png",
                "/icons/images/Blue/white/list/Icon-List-Module_Thumbs_up_RGB_blue_white-circle.png",
                "/icons/images/Blue/white/list/Icon-List-Module_User_authentication_RGB_blue_white-circle.png",
                "/icons/images/Blue/white/list/Icon-List-Module_Web_connected_printer_RGB_blue_white-circle.png",
            ],
            link: [
                "/icons/images/Blue/white/link/Link-Icon-Module_2_Instant-Ink_RGB_blue_white-circle.png",
                "/icons/images/Blue/white/link/Link-Icon-Module_2_Support_RGB_blue_white-circle.png",
                "/icons/images/Blue/white/link/Link-Icon-Module_2_View-Account_RGB_blue_white-circle.png",
                "/icons/images/Blue/white/link/Link-Icon-Module_End_to_end_security_RGB_blue_white-circle.png",
                "/icons/images/Blue/white/link/Link-Icon-Module_Financial_Services_RGB_blue_white-circle.png",
                "/icons/images/Blue/white/link/Link-Icon-Module_Gear_RGB_blue_white-circle.png",
                "/icons/images/Blue/white/link/Link-Icon-Module_Ink_RGB_blue_white-circle.png",
                "/icons/images/Blue/white/link/Link-Icon-Module_Inks_RGB_blue_white-circle.png",
                "/icons/images/Blue/white/link/Link-Icon-Module_Laptop_RGB_blue_white-circle.png",
                "/icons/images/Blue/white/link/Link-Icon-Module_Legendary_HP_relaibility_RGB_blue_white-circle.png",
                "/icons/images/Blue/white/link/Link-Icon-Module_Ok_RGB_blue_white-circle.png",
                "/icons/images/Blue/white/link/Link-Icon-Module_On_the_fly_RGB_blue_white-circle.png",
                "/icons/images/Blue/white/link/Link-Icon-Module_Planet_pillar_RGB_blue_white-circle.png",
                "/icons/images/Blue/white/link/Link-Icon-Module_Printer_RGB_blue_white-circle.png",
                "/icons/images/Blue/white/link/Link-Icon-Module_Quick Setup_RGB_blue_white-circle.png",
                "/icons/images/Blue/white/link/Link-Icon-Module_Repair_RGB_blue_white-circle.png",
                "/icons/images/Blue/white/link/Link-Icon-Module_Setup_supplies_RGB_blue_white-circle.png",
                "/icons/images/Blue/white/link/Link-Icon-Module_Shopping_cart_RGB_blue_white-circle.png",
                "/icons/images/Blue/white/link/Link-Icon-Module_Smart_printer_RGB_blue_white-circle.png",
                "/icons/images/Blue/white/link/Link-Icon-Module_Star_recomendation_RGB_blue_white-circle.png",
                "/icons/images/Blue/white/link/Link-Icon-Module_Sustainable_packaging_RGB_blue_white-circle.png",
                "/icons/images/Blue/white/link/Link-Icon-Module_Thumbs_up_RGB_blue_white-circle.png",
                "/icons/images/Blue/white/link/Link-Icon-Module_User_authentication_RGB_blue_white-circle.png",
                "/icons/images/Blue/white/link/Link-Icon-Module_Web_connected_printer_RGB_blue_white-circle.png",
            ],
        },
    },
    green: {
        white: {
            list: [
                "/icons/images/Green/white/list/Icon-List-Module_2_Support_RGB_green_white-circle.png",
                "/icons/images/Green/white/list/Icon-List-Module_2_View-Account_RGB_green_white-circle.png",
                "/icons/images/Green/white/list/Icon-List-Module_End_to_end_security_RGB_green_white-circle.png",
                "/icons/images/Green/white/list/Icon-List-Module_Financial_Services_RGB_green_white-circle.png",
                "/icons/images/Green/white/list/Icon-List-Module_Gear_RGB_green_white-circle.png",
                "/icons/images/Green/white/list/Icon-List-Module_Ink_RGB_green_white-circle.png",
                "/icons/images/Green/white/list/Icon-List-Module_Inks_RGB_green_white-circle.png",
                "/icons/images/Green/white/list/Icon-List-Module_Instant-Ink_RGB_green_white-circle.png",
                "/icons/images/Green/white/list/Icon-List-Module_Laptop_RGB_green_white-circle.png",
                "/icons/images/Green/white/list/Icon-List-Module_Legendary_HP_relaibility_RGB_green_white-circle.png",
                "/icons/images/Green/white/list/Icon-List-Module_Ok_RGB_green_white-circle.png",
                "/icons/images/Green/white/list/Icon-List-Module_On_the_fly_RGB_green_white-circle.png",
                "/icons/images/Green/white/list/Icon-List-Module_Planet_pillar_RGB_green_white-circle.png",
                "/icons/images/Green/white/list/Icon-List-Module_Printer_RGB_green_white-circle.png",
                "/icons/images/Green/white/list/Icon-List-Module_Quick Setup_RGB_green_white-circle.png",
                "/icons/images/Green/white/list/Icon-List-Module_Repair_RGB_green_white-circle.png",
                "/icons/images/Green/white/list/Icon-List-Module_Setup_supplies_RGB_green_white-circle.png",
                "/icons/images/Green/white/list/Icon-List-Module_Shopping_cart_RGB_green_white-circle.png",
                "/icons/images/Green/white/list/Icon-List-Module_Smart_printer_RGB_green_white-circle.png",
                "/icons/images/Green/white/list/Icon-List-Module_Star_recomendation_RGB_green_white-circle.png",
                "/icons/images/Green/white/list/Icon-List-Module_Sustainable_packaging_RGB_green_white-circle.png",
                "/icons/images/Green/white/list/Icon-List-Module_Thumbs_up_RGB_green_white-circle.png",
                "/icons/images/Green/white/list/Icon-List-Module_User_authentication_RGB_green_white-circle.png",
                "/icons/images/Green/white/list/Icon-List-Module_Web_connected_printer_RGB_green_white-circle.png",
            ],
            link: [
                "/icons/images/Green/white/link/Link-Icon-Module_2_Instant-Ink_RGB_green_white-circle.png",
                "/icons/images/Green/white/link/Link-Icon-Module_2_Support_RGB_green_white-circle.png",
                "/icons/images/Green/white/link/Link-Icon-Module_2_View-Account_RGB_green_white-circle.png",
                "/icons/images/Green/white/link/Link-Icon-Module_End_to_end_security_RGB_green_white-circle.png",
                "/icons/images/Green/white/link/Link-Icon-Module_Financial_Services_RGB_green_white-circle.png",
                "/icons/images/Green/white/link/Link-Icon-Module_Gear_RGB_green_white-circle.png",
                "/icons/images/Green/white/link/Link-Icon-Module_Ink_RGB_green_white-circle.png",
                "/icons/images/Green/white/link/Link-Icon-Module_Inks_RGB_green_white-circle.png",
                "/icons/images/Green/white/link/Link-Icon-Module_Laptop_RGB_green_white-circle.png",
                "/icons/images/Green/white/link/Link-Icon-Module_Legendary_HP_relaibility_RGB_green_white-circle.png",
                "/icons/images/Green/white/link/Link-Icon-Module_Ok_RGB_green_white-circle.png",
                "/icons/images/Green/white/link/Link-Icon-Module_On_the_fly_RGB_green_white-circle.png",
                "/icons/images/Green/white/link/Link-Icon-Module_Planet_pillar_RGB_green_white-circle.png",
                "/icons/images/Green/white/link/Link-Icon-Module_Printer_RGB_green_white-circle.png",
                "/icons/images/Green/white/link/Link-Icon-Module_Quick Setup_RGB_green_white-circle.png",
                "/icons/images/Green/white/link/Link-Icon-Module_Repair_RGB_green_white-circle.png",
                "/icons/images/Green/white/link/Link-Icon-Module_Setup_supplies_RGB_green_white-circle.png",
                "/icons/images/Green/white/link/Link-Icon-Module_Shopping_cart_RGB_green_white-circle.png",
                "/icons/images/Green/white/link/Link-Icon-Module_Smart_printer_RGB_green_white-circle.png",
                "/icons/images/Green/white/link/Link-Icon-Module_Star_recomendation_RGB_green_white-circle.png",
                "/icons/images/Green/white/link/Link-Icon-Module_Sustainable_packaging_RGB_green_white-circle.png",
                "/icons/images/Green/white/link/Link-Icon-Module_Thumbs_up_RGB_green_white-circle.png",
                "/icons/images/Green/white/link/Link-Icon-Module_User_authentication_RGB_green_white-circle.png",
                "/icons/images/Green/white/link/Link-Icon-Module_Web_connected_printer_RGB_green_white-circle.png",
            ],
        },
        color: {
            list: [
                "/icons/images/Green/color/list/Icon-List-Module_2_Support_RGB_black_green-circle.png",
                "/icons/images/Green/color/list/Icon-List-Module_2_View-Account_RGB_black_green-circle.png",
                "/icons/images/Green/color/list/Icon-List-Module_End_to_end_security_RGB_black_green-circle.png",
                "/icons/images/Green/color/list/Icon-List-Module_Financial_Services_RGB_black_green-circle.png",
                "/icons/images/Green/color/list/Icon-List-Module_Gear_RGB_black_green-circle.png",
                "/icons/images/Green/color/list/Icon-List-Module_Ink_RGB_black_green-circle.png",
                "/icons/images/Green/color/list/Icon-List-Module_Inks_RGB_black_green-circle.png",
                "/icons/images/Green/color/list/Icon-List-Module_Instant-Ink_RGB_black_green-circle.png",
                "/icons/images/Green/color/list/Icon-List-Module_Laptop_RGB_black_green-circle.png",
                "/icons/images/Green/color/list/Icon-List-Module_Legendary_HP_relaibility_RGB_black_green-circle.png",
                "/icons/images/Green/color/list/Icon-List-Module_Ok_RGB_black_green-circle.png",
                "/icons/images/Green/color/list/Icon-List-Module_On_the_fly_RGB_black_green-circle.png",
                "/icons/images/Green/color/list/Icon-List-Module_Planet_pillar_RGB_black_green-circle.png",
                "/icons/images/Green/color/list/Icon-List-Module_Printer_RGB_black_green-circle.png",
                "/icons/images/Green/color/list/Icon-List-Module_Quick Setup_RGB_black_green-circle.png",
                "/icons/images/Green/color/list/Icon-List-Module_Repair_RGB_black_green-circle.png",
                "/icons/images/Green/color/list/Icon-List-Module_Setup_supplies_RGB_black_green-circle.png",
                "/icons/images/Green/color/list/Icon-List-Module_Shopping_cart_RGB_black_green-circle.png",
                "/icons/images/Green/color/list/Icon-List-Module_Smart_printer_RGB_black_green-circle.png",
                "/icons/images/Green/color/list/Icon-List-Module_Star_recomendation_RGB_black_green-circle.png",
                "/icons/images/Green/color/list/Icon-List-Module_Sustainable_packaging_RGB_black_green-circle.png",
                "/icons/images/Green/color/list/Icon-List-Module_Thumbs_up_RGB_black_green-circle.png",
                "/icons/images/Green/color/list/Icon-List-Module_User_authentication_RGB_black_green-circle.png",
                "/icons/images/Green/color/list/Icon-List-Module_Web_connected_printer_RGB_black_green-circle.png",
            ],
            link: [
                "/icons/images/Green/color/link/Link-Icon-Module_2_Instant-Ink_RGB_black_green-circle.png",
                "/icons/images/Green/color/link/Link-Icon-Module_2_Support_RGB_black_green-circle.png",
                "/icons/images/Green/color/link/Link-Icon-Module_2_View-Account_RGB_black_green-circle.png",
                "/icons/images/Green/color/link/Link-Icon-Module_End_to_end_security_RGB_black_green-circle.png",
                "/icons/images/Green/color/link/Link-Icon-Module_Financial_Services_RGB_black_green-circle.png",
                "/icons/images/Green/color/link/Link-Icon-Module_Gear_RGB_black_green-circle.png",
                "/icons/images/Green/color/link/Link-Icon-Module_Ink_RGB_black_green-circle.png",
                "/icons/images/Green/color/link/Link-Icon-Module_Inks_RGB_black_green-circle.png",
                "/icons/images/Green/color/link/Link-Icon-Module_Laptop_RGB_black_green-circle.png",
                "/icons/images/Green/color/link/Link-Icon-Module_Legendary_HP_relaibility_RGB_black_green-circle.png",
                "/icons/images/Green/color/link/Link-Icon-Module_Ok_RGB_black_green-circle.png",
                "/icons/images/Green/color/link/Link-Icon-Module_On_the_fly_RGB_black_green-circle.png",
                "/icons/images/Green/color/link/Link-Icon-Module_Planet_pillar_RGB_black_green-circle.png",
                "/icons/images/Green/color/link/Link-Icon-Module_Printer_RGB_black_green-circle.png",
                "/icons/images/Green/color/link/Link-Icon-Module_Quick Setup_RGB_black_green-circle.png",
                "/icons/images/Green/color/link/Link-Icon-Module_Repair_RGB_black_green-circle.png",
                "/icons/images/Green/color/link/Link-Icon-Module_Setup_supplies_RGB_black_green-circle.png",
                "/icons/images/Green/color/link/Link-Icon-Module_Shopping_cart_RGB_black_green-circle.png",
                "/icons/images/Green/color/link/Link-Icon-Module_Smart_printer_RGB_black_green-circle.png",
                "/icons/images/Green/color/link/Link-Icon-Module_Star_recomendation_RGB_black_green-circle.png",
                "/icons/images/Green/color/link/Link-Icon-Module_Sustainable_packaging_RGB_black_green-circle.png",
                "/icons/images/Green/color/link/Link-Icon-Module_Thumbs_up_RGB_black_green-circle.png",
                "/icons/images/Green/color/link/Link-Icon-Module_User_authentication_RGB_black_green-circle.png",
                "/icons/images/Green/color/link/Link-Icon-Module_Web_connected_printer_RGB_black_green-circle.png",
            ],
        },
    },
    lavender: {
        color: {
            link: [
                "/icons/images/Indigo/color/link/Link-Icon-Module_2_Instant-Ink_RGB_black_indigo-circle.png",
                "/icons/images/Indigo/color/link/Link-Icon-Module_2_Support_RGB_black_indigo-circle.png",
                "/icons/images/Indigo/color/link/Link-Icon-Module_2_View-Account_RGB_black_indigo-circle.png",
                "/icons/images/Indigo/color/link/Link-Icon-Module_End_to_end_security_RGB_black_indigo-circle.png",
                "/icons/images/Indigo/color/link/Link-Icon-Module_Financial_Services_RGB_black_indigo-circle.png",
                "/icons/images/Indigo/color/link/Link-Icon-Module_Gear_RGB_black_indigo-circle.png",
                "/icons/images/Indigo/color/link/Link-Icon-Module_Ink_RGB_black_indigo-circle.png",
                "/icons/images/Indigo/color/link/Link-Icon-Module_Inks_RGB_black_indigo-circle.png",
                "/icons/images/Indigo/color/link/Link-Icon-Module_Laptop_RGB_black_indigo-circle.png",
                "/icons/images/Indigo/color/link/Link-Icon-Module_Legendary_HP_relaibility_RGB_black_indigo-circle.png",
                "/icons/images/Indigo/color/link/Link-Icon-Module_Ok_RGB_black_indigo-circle.png",
                "/icons/images/Indigo/color/link/Link-Icon-Module_On_the_fly_RGB_black_indigo-circle.png",
                "/icons/images/Indigo/color/link/Link-Icon-Module_Planet_pillar_RGB_black_indigo-circle.png",
                "/icons/images/Indigo/color/link/Link-Icon-Module_Printer_RGB_black_indigo-circle.png",
                "/icons/images/Indigo/color/link/Link-Icon-Module_Quick Setup_RGB_black_indigo-circle.png",
                "/icons/images/Indigo/color/link/Link-Icon-Module_Repair_RGB_black_indigo-circle.png",
                "/icons/images/Indigo/color/link/Link-Icon-Module_Setup_supplies_RGB_black_indigo-circle.png",
                "/icons/images/Indigo/color/link/Link-Icon-Module_Shopping_cart_RGB_black_indigo-circle.png",
                "/icons/images/Indigo/color/link/Link-Icon-Module_Smart_printer_RGB_black_indigo-circle.png",
                "/icons/images/Indigo/color/link/Link-Icon-Module_Star_recomendation_RGB_black_indigo-circle.png",
                "/icons/images/Indigo/color/link/Link-Icon-Module_Sustainable_packaging_RGB_black_indigo-circle.png",
                "/icons/images/Indigo/color/link/Link-Icon-Module_Thumbs_up_RGB_black_indigo-circle.png",
                "/icons/images/Indigo/color/link/Link-Icon-Module_User_authentication_RGB_black_indigo-circle.png",
                "/icons/images/Indigo/color/link/Link-Icon-Module_Web_connected_printer_RGB_black_indigo-circle.png",
            ],
            list: [
                "/icons/images/Indigo/color/list/Icon-List-Module_2_Support_RGB_black_indigo-circle.png",
                "/icons/images/Indigo/color/list/Icon-List-Module_2_View-Account_RGB_black_indigo-circle.png",
                "/icons/images/Indigo/color/list/Icon-List-Module_End_to_end_security_RGB_black_indigo-circle.png",
                "/icons/images/Indigo/color/list/Icon-List-Module_Financial_Services_RGB_black_indigo-circle.png",
                "/icons/images/Indigo/color/list/Icon-List-Module_Gear_RGB_black_indigo-circle.png",
                "/icons/images/Indigo/color/list/Icon-List-Module_Ink_RGB_black_indigo-circle.png",
                "/icons/images/Indigo/color/list/Icon-List-Module_Inks_RGB_black_indigo-circle.png",
                "/icons/images/Indigo/color/list/Icon-List-Module_Instant-Ink_RGB_black_indigo-circle.png",
                "/icons/images/Indigo/color/list/Icon-List-Module_Laptop_RGB_black_indigo-circle.png",
                "/icons/images/Indigo/color/list/Icon-List-Module_Legendary_HP_relaibility_RGB_black_indigo-circle.png",
                "/icons/images/Indigo/color/list/Icon-List-Module_Ok_RGB_black_indigo-circle.png",
                "/icons/images/Indigo/color/list/Icon-List-Module_On_the_fly_RGB_black_indigo-circle.png",
                "/icons/images/Indigo/color/list/Icon-List-Module_Planet_pillar_RGB_black_indigo-circle.png",
                "/icons/images/Indigo/color/list/Icon-List-Module_Printer_RGB_black_indigo-circle.png",
                "/icons/images/Indigo/color/list/Icon-List-Module_Quick Setup_RGB_black_indigo-circle.png",
                "/icons/images/Indigo/color/list/Icon-List-Module_Repair_RGB_black_indigo-circle.png",
                "/icons/images/Indigo/color/list/Icon-List-Module_Setup_supplies_RGB_black_indigo-circle.png",
                "/icons/images/Indigo/color/list/Icon-List-Module_Shopping_cart_RGB_black_indigo-circle.png",
                "/icons/images/Indigo/color/list/Icon-List-Module_Smart_printer_RGB_black_indigo-circle.png",
                "/icons/images/Indigo/color/list/Icon-List-Module_Star_recomendation_RGB_black_indigo-circle.png",
                "/icons/images/Indigo/color/list/Icon-List-Module_Sustainable_packaging_RGB_black_indigo-circle.png",
                "/icons/images/Indigo/color/list/Icon-List-Module_Thumbs_up_RGB_black_indigo-circle.png",
                "/icons/images/Indigo/color/list/Icon-List-Module_User_authentication_RGB_black_indigo-circle.png",
                "/icons/images/Indigo/color/list/Icon-List-Module_Web_connected_printer_RGB_black_indigo-circle.png",
            ],
        },
        white: {
            link: [
                "/icons/images/Indigo/white/link/Link-Icon-Module_2_Instant-Ink_RGB_indigo_white-circle.png",
                "/icons/images/Indigo/white/link/Link-Icon-Module_2_Support_RGB_indigo_white-circle.png",
                "/icons/images/Indigo/white/link/Link-Icon-Module_2_View-Account_RGB_indigo_white-circle.png",
                "/icons/images/Indigo/white/link/Link-Icon-Module_End_to_end_security_RGB_indigo_white-circle.png",
                "/icons/images/Indigo/white/link/Link-Icon-Module_Financial_Services_RGB_indigo_white-circle.png",
                "/icons/images/Indigo/white/link/Link-Icon-Module_Gear_RGB_indigo_white-circle.png",
                "/icons/images/Indigo/white/link/Link-Icon-Module_Ink_RGB_indigo_white-circle.png",
                "/icons/images/Indigo/white/link/Link-Icon-Module_Inks_RGB_indigo_white-circle.png",
                "/icons/images/Indigo/white/link/Link-Icon-Module_Laptop_RGB_indigo_white-circle.png",
                "/icons/images/Indigo/white/link/Link-Icon-Module_Legendary_HP_relaibility_RGB_indigo_white-circle.png",
                "/icons/images/Indigo/white/link/Link-Icon-Module_Ok_RGB_indigo_white-circle.png",
                "/icons/images/Indigo/white/link/Link-Icon-Module_On_the_fly_RGB_indigo_white-circle.png",
                "/icons/images/Indigo/white/link/Link-Icon-Module_Planet_pillar_RGB_indigo_white-circle.png",
                "/icons/images/Indigo/white/link/Link-Icon-Module_Printer_RGB_indigo_white-circle.png",
                "/icons/images/Indigo/white/link/Link-Icon-Module_Quick Setup_RGB_indigo_white-circle.png",
                "/icons/images/Indigo/white/link/Link-Icon-Module_Repair_RGB_indigo_white-circle.png",
                "/icons/images/Indigo/white/link/Link-Icon-Module_Setup_supplies_RGB_indigo_white-circle.png",
                "/icons/images/Indigo/white/link/Link-Icon-Module_Shopping_cart_RGB_indigo_white-circle.png",
                "/icons/images/Indigo/white/link/Link-Icon-Module_Smart_printer_RGB_indigo_white-circle.png",
                "/icons/images/Indigo/white/link/Link-Icon-Module_Star_recomendation_RGB_indigo_white-circle.png",
                "/icons/images/Indigo/white/link/Link-Icon-Module_Sustainable_packaging_RGB_indigo_white-circle.png",
                "/icons/images/Indigo/white/link/Link-Icon-Module_Thumbs_up_RGB_indigo_white-circle.png",
                "/icons/images/Indigo/white/link/Link-Icon-Module_User_authentication_RGB_indigo_white-circle.png",
                "/icons/images/Indigo/white/link/Link-Icon-Module_Web_connected_printer_RGB_indigo_white-circle.png",
            ],
            list: [
                "/icons/images/Indigo/white/list/Icon-List-Module_2_Support_RGB_indigo_white-circle.png",
                "/icons/images/Indigo/white/list/Icon-List-Module_2_View-Account_RGB_indigo_white-circle.png",
                "/icons/images/Indigo/white/list/Icon-List-Module_End_to_end_security_RGB_indigo_white-circle.png",
                "/icons/images/Indigo/white/list/Icon-List-Module_Financial_Services_RGB_indigo_white-circle.png",
                "/icons/images/Indigo/white/list/Icon-List-Module_Gear_RGB_indigo_white-circle.png",
                "/icons/images/Indigo/white/list/Icon-List-Module_Ink_RGB_indigo_white-circle.png",
                "/icons/images/Indigo/white/list/Icon-List-Module_Inks_RGB_indigo_white-circle.png",
                "/icons/images/Indigo/white/list/Icon-List-Module_Instant-Ink_RGB_indigo_white-circle.png",
                "/icons/images/Indigo/white/list/Icon-List-Module_Laptop_RGB_indigo_white-circle.png",
                "/icons/images/Indigo/white/list/Icon-List-Module_Legendary_HP_relaibility_RGB_indigo_white-circle.png",
                "/icons/images/Indigo/white/list/Icon-List-Module_Ok_RGB_indigo_white-circle.png",
                "/icons/images/Indigo/white/list/Icon-List-Module_On_the_fly_RGB_indigo_white-circle.png",
                "/icons/images/Indigo/white/list/Icon-List-Module_Planet_pillar_RGB_indigo_white-circle.png",
                "/icons/images/Indigo/white/list/Icon-List-Module_Printer_RGB_indigo_white-circle.png",
                "/icons/images/Indigo/white/list/Icon-List-Module_Quick Setup_RGB_indigo_white-circle.png",
                "/icons/images/Indigo/white/list/Icon-List-Module_Repair_RGB_indigo_white-circle.png",
                "/icons/images/Indigo/white/list/Icon-List-Module_Setup_supplies_RGB_indigo_white-circle.png",
                "/icons/images/Indigo/white/list/Icon-List-Module_Shopping_cart_RGB_indigo_white-circle.png",
                "/icons/images/Indigo/white/list/Icon-List-Module_Smart_printer_RGB_indigo_white-circle.png",
                "/icons/images/Indigo/white/list/Icon-List-Module_Star_recomendation_RGB_indigo_white-circle.png",
                "/icons/images/Indigo/white/list/Icon-List-Module_Sustainable_packaging_RGB_indigo_white-circle.png",
                "/icons/images/Indigo/white/list/Icon-List-Module_Thumbs_up_RGB_indigo_white-circle.png",
                "/icons/images/Indigo/white/list/Icon-List-Module_User_authentication_RGB_indigo_white-circle.png",
                "/icons/images/Indigo/white/list/Icon-List-Module_Web_connected_printer_RGB_indigo_white-circle.png",
            ],
        },
    },
    pink: {
        color: {
            list: [
                "/icons/images/Pink/color/list/Icon-List-Module_2_Support_RGB_black_pink-circle.png",
                "/icons/images/Pink/color/list/Icon-List-Module_2_View-Account_RGB_black_pink-circle.png",
                "/icons/images/Pink/color/list/Icon-List-Module_End_to_end_security_RGB_black_pink-circle.png",
                "/icons/images/Pink/color/list/Icon-List-Module_Financial_Services_RGB_black_pink-circle.png",
                "/icons/images/Pink/color/list/Icon-List-Module_Gear_RGB_black_pink-circle.png",
                "/icons/images/Pink/color/list/Icon-List-Module_Ink_RGB_black_pink-circle.png",
                "/icons/images/Pink/color/list/Icon-List-Module_Inks_RGB_black_pink-circle.png",
                "/icons/images/Pink/color/list/Icon-List-Module_Instant-Ink_RGB_black_pink-circle.png",
                "/icons/images/Pink/color/list/Icon-List-Module_Laptop_RGB_black_pink-circle.png",
                "/icons/images/Pink/color/list/Icon-List-Module_Legendary_HP_relaibility_RGB_black_pink-circle.png",
                "/icons/images/Pink/color/list/Icon-List-Module_Ok_RGB_black_pink-circle.png",
                "/icons/images/Pink/color/list/Icon-List-Module_On_the_fly_RGB_black_pink-circle.png",
                "/icons/images/Pink/color/list/Icon-List-Module_Planet_pillar_RGB_black_pink-circle.png",
                "/icons/images/Pink/color/list/Icon-List-Module_Printer_RGB_black_pink-circle.png",
                "/icons/images/Pink/color/list/Icon-List-Module_Quick Setup_RGB_black_pink-circle.png",
                "/icons/images/Pink/color/list/Icon-List-Module_Repair_RGB_black_pink-circle.png",
                "/icons/images/Pink/color/list/Icon-List-Module_Setup_supplies_RGB_black_pink-circle.png",
                "/icons/images/Pink/color/list/Icon-List-Module_Shopping_cart_RGB_black_pink-circle.png",
                "/icons/images/Pink/color/list/Icon-List-Module_Smart_printer_RGB_black_pink-circle.png",
                "/icons/images/Pink/color/list/Icon-List-Module_Star_recomendation_RGB_black_pink-circle.png",
                "/icons/images/Pink/color/list/Icon-List-Module_Sustainable_packaging_RGB_black_pink-circle.png",
                "/icons/images/Pink/color/list/Icon-List-Module_Thumbs_up_RGB_black_pink-circle.png",
                "/icons/images/Pink/color/list/Icon-List-Module_User_authentication_RGB_black_pink-circle.png",
                "/icons/images/Pink/color/list/Icon-List-Module_Web_connected_printer_RGB_black_pink-circle.png",
            ],
            link: [
                "/icons/images/Pink/color/link/Link-Icon-Module_2_Instant-Ink_RGB_black_pink-circle.png",
                "/icons/images/Pink/color/link/Link-Icon-Module_2_Support_RGB_black_pink-circle.png",
                "/icons/images/Pink/color/link/Link-Icon-Module_2_View-Account_RGB_black_pink-circle.png",
                "/icons/images/Pink/color/link/Link-Icon-Module_End_to_end_security_RGB_black_pink-circle.png",
                "/icons/images/Pink/color/link/Link-Icon-Module_Financial_Services_RGB_black_pink-circle.png",
                "/icons/images/Pink/color/link/Link-Icon-Module_Gear_RGB_black_pink-circle.png",
                "/icons/images/Pink/color/link/Link-Icon-Module_Ink_RGB_black_pink-circle.png",
                "/icons/images/Pink/color/link/Link-Icon-Module_Inks_RGB_black_pink-circle.png",
                "/icons/images/Pink/color/link/Link-Icon-Module_Laptop_RGB_black_pink-circle.png",
                "/icons/images/Pink/color/link/Link-Icon-Module_Legendary_HP_relaibility_RGB_black_pink-circle.png",
                "/icons/images/Pink/color/link/Link-Icon-Module_Ok_RGB_black_pink-circle.png",
                "/icons/images/Pink/color/link/Link-Icon-Module_On_the_fly_RGB_black_pink-circle.png",
                "/icons/images/Pink/color/link/Link-Icon-Module_Planet_pillar_RGB_black_pink-circle.png",
                "/icons/images/Pink/color/link/Link-Icon-Module_Printer_RGB_black_pink-circle.png",
                "/icons/images/Pink/color/link/Link-Icon-Module_Quick Setup_RGB_black_pink-circle.png",
                "/icons/images/Pink/color/link/Link-Icon-Module_Repair_RGB_black_pink-circle.png",
                "/icons/images/Pink/color/link/Link-Icon-Module_Setup_supplies_RGB_black_pink-circle.png",
                "/icons/images/Pink/color/link/Link-Icon-Module_Shopping_cart_RGB_black_pink-circle.png",
                "/icons/images/Pink/color/link/Link-Icon-Module_Smart_printer_RGB_black_pink-circle.png",
                "/icons/images/Pink/color/link/Link-Icon-Module_Star_recomendation_RGB_black_pink-circle.png",
                "/icons/images/Pink/color/link/Link-Icon-Module_Sustainable_packaging_RGB_black_pink-circle.png",
                "/icons/images/Pink/color/link/Link-Icon-Module_Thumbs_up_RGB_black_pink-circle.png",
                "/icons/images/Pink/color/link/Link-Icon-Module_User_authentication_RGB_black_pink-circle.png",
                "/icons/images/Pink/color/link/Link-Icon-Module_Web_connected_printer_RGB_black_pink-circle.png",
            ],
        },
        white: {
            link: [
                "/icons/images/Pink/white/link/Link-Icon-Module_2_Instant-Ink_RGB_pink_white-circle.png",
                "/icons/images/Pink/white/link/Link-Icon-Module_2_Support_RGB_pink_white-circle.png",
                "/icons/images/Pink/white/link/Link-Icon-Module_2_View-Account_RGB_pink_white-circle.png",
                "/icons/images/Pink/white/link/Link-Icon-Module_End_to_end_security_RGB_pink_white-circle.png",
                "/icons/images/Pink/white/link/Link-Icon-Module_Financial_Services_RGB_pink_white-circle.png",
                "/icons/images/Pink/white/link/Link-Icon-Module_Gear_RGB_pink_white-circle.png",
                "/icons/images/Pink/white/link/Link-Icon-Module_Ink_RGB_pink_white-circle.png",
                "/icons/images/Pink/white/link/Link-Icon-Module_Inks_RGB_pink_white-circle.png",
                "/icons/images/Pink/white/link/Link-Icon-Module_Laptop_RGB_pink_white-circle.png",
                "/icons/images/Pink/white/link/Link-Icon-Module_Legendary_HP_relaibility_RGB_pink_white-circle.png",
                "/icons/images/Pink/white/link/Link-Icon-Module_Ok_RGB_pink_white-circle.png",
                "/icons/images/Pink/white/link/Link-Icon-Module_On_the_fly_RGB_pink_white-circle.png",
                "/icons/images/Pink/white/link/Link-Icon-Module_Planet_pillar_RGB_pink_white-circle.png",
                "/icons/images/Pink/white/link/Link-Icon-Module_Printer_RGB_pink_white-circle.png",
                "/icons/images/Pink/white/link/Link-Icon-Module_Quick Setup_RGB_pink_white-circle.png",
                "/icons/images/Pink/white/link/Link-Icon-Module_Repair_RGB_pink_white-circle.png",
                "/icons/images/Pink/white/link/Link-Icon-Module_Setup_supplies_RGB_pink_white-circle.png",
                "/icons/images/Pink/white/link/Link-Icon-Module_Shopping_cart_RGB_pink_white-circle.png",
                "/icons/images/Pink/white/link/Link-Icon-Module_Smart_printer_RGB_pink_white-circle.png",
                "/icons/images/Pink/white/link/Link-Icon-Module_Star_recomendation_RGB_pink_white-circle.png",
                "/icons/images/Pink/white/link/Link-Icon-Module_Sustainable_packaging_RGB_pink_white-circle.png",
                "/icons/images/Pink/white/link/Link-Icon-Module_Thumbs_up_RGB_pink_white-circle.png",
                "/icons/images/Pink/white/link/Link-Icon-Module_User_authentication_RGB_pink_white-circle.png",
                "/icons/images/Pink/white/link/Link-Icon-Module_Web_connected_printer_RGB_pink_white-circle.png",
            ],
            list: [
                "/icons/images/Pink/white/list/Icon-List-Module_2_Support_RGB_pink_white-circle.png",
                "/icons/images/Pink/white/list/Icon-List-Module_2_View-Account_RGB_pink_white-circle.png",
                "/icons/images/Pink/white/list/Icon-List-Module_End_to_end_security_RGB_pink_white-circle.png",
                "/icons/images/Pink/white/list/Icon-List-Module_Financial_Services_RGB_pink_white-circle.png",
                "/icons/images/Pink/white/list/Icon-List-Module_Gear_RGB_pink_white-circle.png",
                "/icons/images/Pink/white/list/Icon-List-Module_Ink_RGB_pink_white-circle.png",
                "/icons/images/Pink/white/list/Icon-List-Module_Inks_RGB_pink_white-circle.png",
                "/icons/images/Pink/white/list/Icon-List-Module_Instant-Ink_RGB_pink_white-circle.png",
                "/icons/images/Pink/white/list/Icon-List-Module_Laptop_RGB_pink_white-circle.png",
                "/icons/images/Pink/white/list/Icon-List-Module_Legendary_HP_relaibility_RGB_pink_white-circle.png",
                "/icons/images/Pink/white/list/Icon-List-Module_Ok_RGB_pink_white-circle.png",
                "/icons/images/Pink/white/list/Icon-List-Module_On_the_fly_RGB_pink_white-circle.png",
                "/icons/images/Pink/white/list/Icon-List-Module_Planet_pillar_RGB_pink_white-circle.png",
                "/icons/images/Pink/white/list/Icon-List-Module_Printer_RGB_pink_white-circle.png",
                "/icons/images/Pink/white/list/Icon-List-Module_Quick Setup_RGB_pink_white-circle.png",
                "/icons/images/Pink/white/list/Icon-List-Module_Repair_RGB_pink_white-circle.png",
                "/icons/images/Pink/white/list/Icon-List-Module_Setup_supplies_RGB_pink_white-circle.png",
                "/icons/images/Pink/white/list/Icon-List-Module_Shopping_cart_RGB_pink_white-circle.png",
                "/icons/images/Pink/white/list/Icon-List-Module_Smart_printer_RGB_pink_white-circle.png",
                "/icons/images/Pink/white/list/Icon-List-Module_Star_recomendation_RGB_pink_white-circle.png",
                "/icons/images/Pink/white/list/Icon-List-Module_Sustainable_packaging_RGB_pink_white-circle.png",
                "/icons/images/Pink/white/list/Icon-List-Module_Thumbs_up_RGB_pink_white-circle.png",
                "/icons/images/Pink/white/list/Icon-List-Module_User_authentication_RGB_pink_white-circle.png",
                "/icons/images/Pink/white/list/Icon-List-Module_Web_connected_printer_RGB_pink_white-circle.png",
            ],
        },
    },
    purple: {
        white: {
            list: [
                "/icons/images/Purple/white/list/Icon-List-Module_2_Support_RGB_purple_white-circle.png",
                "/icons/images/Purple/white/list/Icon-List-Module_2_View-Account_RGB_purple_white-circle.png",
                "/icons/images/Purple/white/list/Icon-List-Module_End_to_end_security_RGB_purple_white-circle.png",
                "/icons/images/Purple/white/list/Icon-List-Module_Financial_Services_RGB_purple_white-circle.png",
                "/icons/images/Purple/white/list/Icon-List-Module_Gear_RGB_purple_white-circle.png",
                "/icons/images/Purple/white/list/Icon-List-Module_Ink_RGB_purple_white-circle.png",
                "/icons/images/Purple/white/list/Icon-List-Module_Inks_RGB_purple_white-circle.png",
                "/icons/images/Purple/white/list/Icon-List-Module_Instant-Ink_RGB_purple_white-circle.png",
                "/icons/images/Purple/white/list/Icon-List-Module_Laptop_RGB_purple_white-circle.png",
                "/icons/images/Purple/white/list/Icon-List-Module_Legendary_HP_relaibility_RGB_purple_white-circle.png",
                "/icons/images/Purple/white/list/Icon-List-Module_Ok_RGB_purple_white-circle.png",
                "/icons/images/Purple/white/list/Icon-List-Module_On_the_fly_RGB_purple_white-circle.png",
                "/icons/images/Purple/white/list/Icon-List-Module_Planet_pillar_RGB_purple_white-circle.png",
                "/icons/images/Purple/white/list/Icon-List-Module_Printer_RGB_purple_white-circle.png",
                "/icons/images/Purple/white/list/Icon-List-Module_Quick Setup_RGB_purple_white-circle.png",
                "/icons/images/Purple/white/list/Icon-List-Module_Repair_RGB_purple_white-circle.png",
                "/icons/images/Purple/white/list/Icon-List-Module_Setup_supplies_RGB_purple_white-circle.png",
                "/icons/images/Purple/white/list/Icon-List-Module_Shopping_cart_RGB_purple_white-circle.png",
                "/icons/images/Purple/white/list/Icon-List-Module_Smart_printer_RGB_purple_white-circle.png",
                "/icons/images/Purple/white/list/Icon-List-Module_Star_recomendation_RGB_purple_white-circle.png",
                "/icons/images/Purple/white/list/Icon-List-Module_Sustainable_packaging_RGB_purple_white-circle.png",
                "/icons/images/Purple/white/list/Icon-List-Module_Thumbs_up_RGB_purple_white-circle.png",
                "/icons/images/Purple/white/list/Icon-List-Module_User_authentication_RGB_purple_white-circle.png",
                "/icons/images/Purple/white/list/Icon-List-Module_Web_connected_printer_RGB_purple_white-circle.png",
            ],
            link: [
                "/icons/images/Purple/white/link/Link-Icon-Module_2_Instant-Ink_RGB_purple_white-circle.png",
                "/icons/images/Purple/white/link/Link-Icon-Module_2_Support_RGB_purple_white-circle.png",
                "/icons/images/Purple/white/link/Link-Icon-Module_2_View-Account_RGB_purple_white-circle.png",
                "/icons/images/Purple/white/link/Link-Icon-Module_End_to_end_security_RGB_purple_white-circle.png",
                "/icons/images/Purple/white/link/Link-Icon-Module_Financial_Services_RGB_purple_white-circle.png",
                "/icons/images/Purple/white/link/Link-Icon-Module_Gear_RGB_purple_white-circle.png",
                "/icons/images/Purple/white/link/Link-Icon-Module_Ink_RGB_purple_white-circle.png",
                "/icons/images/Purple/white/link/Link-Icon-Module_Inks_RGB_purple_white-circle.png",
                "/icons/images/Purple/white/link/Link-Icon-Module_Laptop_RGB_purple_white-circle.png",
                "/icons/images/Purple/white/link/Link-Icon-Module_Legendary_HP_relaibility_RGB_purple_white-circle.png",
                "/icons/images/Purple/white/link/Link-Icon-Module_Ok_RGB_purple_white-circle.png",
                "/icons/images/Purple/white/link/Link-Icon-Module_On_the_fly_RGB_purple_white-circle.png",
                "/icons/images/Purple/white/link/Link-Icon-Module_Planet_pillar_RGB_purple_white-circle.png",
                "/icons/images/Purple/white/link/Link-Icon-Module_Printer_RGB_purple_white-circle.png",
                "/icons/images/Purple/white/link/Link-Icon-Module_Quick Setup_RGB_purple_white-circle.png",
                "/icons/images/Purple/white/link/Link-Icon-Module_Repair_RGB_purple_white-circle.png",
                "/icons/images/Purple/white/link/Link-Icon-Module_Setup_supplies_RGB_purple_white-circle.png",
                "/icons/images/Purple/white/link/Link-Icon-Module_Shopping_cart_RGB_purple_white-circle.png",
                "/icons/images/Purple/white/link/Link-Icon-Module_Smart_printer_RGB_purple_white-circle.png",
                "/icons/images/Purple/white/link/Link-Icon-Module_Star_recomendation_RGB_purple_white-circle.png",
                "/icons/images/Purple/white/link/Link-Icon-Module_Sustainable_packaging_RGB_purple_white-circle.png",
                "/icons/images/Purple/white/link/Link-Icon-Module_Thumbs_up_RGB_purple_white-circle.png",
                "/icons/images/Purple/white/link/Link-Icon-Module_User_authentication_RGB_purple_white-circle.png",
                "/icons/images/Purple/white/link/Link-Icon-Module_Web_connected_printer_RGB_purple_white-circle.png",
            ],
        },
        color: {
            list: [
                "/icons/images/Purple/color/list/Icon-List-Module_2_Support_RGB_black_purple-circle.png",
                "/icons/images/Purple/color/list/Icon-List-Module_2_View-Account_RGB_black_purple-circle.png",
                "/icons/images/Purple/color/list/Icon-List-Module_End_to_end_security_RGB_black_purple-circle.png",
                "/icons/images/Purple/color/list/Icon-List-Module_Financial_Services_RGB_black_purple-circle.png",
                "/icons/images/Purple/color/list/Icon-List-Module_Gear_RGB_black_purple-circle.png",
                "/icons/images/Purple/color/list/Icon-List-Module_Ink_RGB_black_purple-circle.png",
                "/icons/images/Purple/color/list/Icon-List-Module_Inks_RGB_black_purple-circle.png",
                "/icons/images/Purple/color/list/Icon-List-Module_Instant-Ink_RGB_black_purple-circle.png",
                "/icons/images/Purple/color/list/Icon-List-Module_Laptop_RGB_black_purple-circle.png",
                "/icons/images/Purple/color/list/Icon-List-Module_Legendary_HP_relaibility_RGB_black_purple-circle.png",
                "/icons/images/Purple/color/list/Icon-List-Module_Ok_RGB_black_purple-circle.png",
                "/icons/images/Purple/color/list/Icon-List-Module_On_the_fly_RGB_black_purple-circle.png",
                "/icons/images/Purple/color/list/Icon-List-Module_Planet_pillar_RGB_black_purple-circle.png",
                "/icons/images/Purple/color/list/Icon-List-Module_Printer_RGB_black_purple-circle.png",
                "/icons/images/Purple/color/list/Icon-List-Module_Quick Setup_RGB_black_purple-circle.png",
                "/icons/images/Purple/color/list/Icon-List-Module_Repair_RGB_black_purple-circle.png",
                "/icons/images/Purple/color/list/Icon-List-Module_Setup_supplies_RGB_black_purple-circle.png",
                "/icons/images/Purple/color/list/Icon-List-Module_Shopping_cart_RGB_black_purple-circle.png",
                "/icons/images/Purple/color/list/Icon-List-Module_Smart_printer_RGB_black_purple-circle.png",
                "/icons/images/Purple/color/list/Icon-List-Module_Star_recomendation_RGB_black_purple-circle.png",
                "/icons/images/Purple/color/list/Icon-List-Module_Sustainable_packaging_RGB_black_purple-circle.png",
                "/icons/images/Purple/color/list/Icon-List-Module_Thumbs_up_RGB_black_purple-circle.png",
                "/icons/images/Purple/color/list/Icon-List-Module_User_authentication_RGB_black_purple-circle.png",
                "/icons/images/Purple/color/list/Icon-List-Module_Web_connected_printer_RGB_black_purple-circle.png",
            ],
            link: [
                "/icons/images/Purple/color/link/Link-Icon-Module_2_Instant-Ink_RGB_black_purple-circle.png",
                "/icons/images/Purple/color/link/Link-Icon-Module_2_Support_RGB_black_purple-circle.png",
                "/icons/images/Purple/color/link/Link-Icon-Module_2_View-Account_RGB_black_purple-circle.png",
                "/icons/images/Purple/color/link/Link-Icon-Module_End_to_end_security_RGB_black_purple-circle.png",
                "/icons/images/Purple/color/link/Link-Icon-Module_Financial_Services_RGB_black_purple-circle.png",
                "/icons/images/Purple/color/link/Link-Icon-Module_Gear_RGB_black_purple-circle.png",
                "/icons/images/Purple/color/link/Link-Icon-Module_Ink_RGB_black_purple-circle.png",
                "/icons/images/Purple/color/link/Link-Icon-Module_Inks_RGB_black_purple-circle.png",
                "/icons/images/Purple/color/link/Link-Icon-Module_Laptop_RGB_black_purple-circle.png",
                "/icons/images/Purple/color/link/Link-Icon-Module_Legendary_HP_relaibility_RGB_black_purple-circle.png",
                "/icons/images/Purple/color/link/Link-Icon-Module_Ok_RGB_black_purple-circle.png",
                "/icons/images/Purple/color/link/Link-Icon-Module_On_the_fly_RGB_black_purple-circle.png",
                "/icons/images/Purple/color/link/Link-Icon-Module_Planet_pillar_RGB_black_purple-circle.png",
                "/icons/images/Purple/color/link/Link-Icon-Module_Printer_RGB_black_purple-circle.png",
                "/icons/images/Purple/color/link/Link-Icon-Module_Quick Setup_RGB_black_purple-circle.png",
                "/icons/images/Purple/color/link/Link-Icon-Module_Repair_RGB_black_purple-circle.png",
                "/icons/images/Purple/color/link/Link-Icon-Module_Setup_supplies_RGB_black_purple-circle.png",
                "/icons/images/Purple/color/link/Link-Icon-Module_Shopping_cart_RGB_black_purple-circle.png",
                "/icons/images/Purple/color/link/Link-Icon-Module_Smart_printer_RGB_black_purple-circle.png",
                "/icons/images/Purple/color/link/Link-Icon-Module_Star_recomendation_RGB_black_purple-circle.png",
                "/icons/images/Purple/color/link/Link-Icon-Module_Sustainable_packaging_RGB_black_purple-circle.png",
                "/icons/images/Purple/color/link/Link-Icon-Module_Thumbs_up_RGB_black_purple-circle.png",
                "/icons/images/Purple/color/link/Link-Icon-Module_User_authentication_RGB_black_purple-circle.png",
                "/icons/images/Purple/color/link/Link-Icon-Module_Web_connected_printer_RGB_black_purple-circle.png",
            ],
        },
    },
};
